#master Commit messages should be of the form  [CurrentSprint:TaskID] Commit Message.

diff --git a/custom-hooks/pre-commit b/custom-hooks/pre-commit
--- a/custom-hooks/pre-commit
+++ b/custom-hooks/pre-commit
@@ -1,23 +1,23 @@
 #!/bin/bash
 
-# generate docs
+# run tests
 function tests {
   printf "\n Starting pre-commit checks..\n"
   npm test
 
   if [ "$?" != "0" ]; then
-    printf "\nThe script returned non-zero error code!" >&2
+    printf "\nTests have failed, please review and fix before commitng again." >&2
     exit 1
   fi
 }
 
-# generate docs
+# lint source code
 function lint {
   printf "\nTests have passed, linting source-code..\n"
   npm run lint
 
   if [ "$?" != "0" ]; then
-    printf "\nThe script returned non-zero error code!" >&2
+    printf "\nLinting task has failed, please review code-style and fix." >&2
     exit 1
   fi
 }
@@ -25,7 +25,7 @@ function lint {
 # generate docs
 function docs {
   printf "\nAlmost there, generating documentation..\n"
-  npm run docs
+  npm run docs ; git add .
 }
 
 tests
